## *Learning basic R to start a data analytics project. Here you will find how to use basic variables at a high level.*

In [74]:
#basic variables
x <- 5  #input as integer
x

y <- "test" #input as String
y

x <- "Hello"
y <- "World"
paste(x," ",y) #string concatenation

[1] 5

[1] "test"

[1] "Hello   World"

In [75]:
# a lil bit more complicated
x <- TRUE #input as Boolean
x

if(x == TRUE){"Positive"} #basic if statement

# vectors
v <- c(1,2,3) #basic vectors
v
v[1] #starts from 1 not 0

#dictionary
l <- list(a=1,b=2,c=3) #basic dictionary
l[["b"]]

l <- list(name = "Shom", title = "King")
l[["title"]]

l$title <- "Duke"
l[["title"]]

[1] TRUE

[1] "Positive"

[1] 1 2 3

[1] 1

[1] 2

[1] "King"

[1] "Duke"

In [76]:
#  data frames
df <- data.frame(name=c("Shom","Elizabeth"),title=c("King","Queen"))

df$name
df$title

df[1,] #first row
df[1,1] #first row first column

df[2,]  #second row

df[nrow(df)+1, ] <- c("x","position") #add to the end.

df[3,] #thrid row

paste(df, collapse=" ") #paste in one line

[1] "Shom"      "Elizabeth"

[1] "King"  "Queen"

  name title
1 Shom King

[1] "Shom"

  name      title
2 Elizabeth Queen

  name title
3 x    position

[1] "c(\"Shom\", \"Elizabeth\", \"x\") c(\"King\", \"Queen\", \"position\")"

In [77]:
name <- readline() #basic read input
if(name == "x") {"its x"} else {"oh its not x"}

y

[1] "oh its not x"

In [78]:
x <- 7
y <- 5
print(x*y) #multiplication
print(x**y) #exponent

[1] 35
[1] 16807

In [79]:
x <- readline("Please enter a number: ") #basic input and for loop
for(i in 1:x) {print(i)}

Please enter a number: 5
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

In [80]:
#basic Function
f1 <- function() { print("Basic function")}
f1()

x <- readline("Please enter a name : ")
f2 <- function(x) { paste("Hello ",x)}
f2(x)

#fucntion with loop
x <- readline("Please enter a number : ")
f3 <- function(x) {
  for(i in 1:x) {
    print(paste("i equals to ", i))
    }
  }

f3(x)

[1] "Basic function"
Please enter a name : Shoimya

[1] "Hello  Shoimya"

Please enter a number : 12
[1] "i equals to  1"
[1] "i equals to  2"
[1] "i equals to  3"
[1] "i equals to  4"
[1] "i equals to  5"
[1] "i equals to  6"
[1] "i equals to  7"
[1] "i equals to  8"
[1] "i equals to  9"
[1] "i equals to  10"
[1] "i equals to  11"
[1] "i equals to  12"

In [81]:
#lets try something a bit more complex
x <- as.numeric(readline("Please enter a number : ")) #
divideCheck <- function(x) {
  if (x %% 2 == 0) {
    print(paste(x, " is even."))
  }
  else if(x %% 3 == 0){
    print(paste(x, " is odd and divisble by 3."))
  }
  else{
    print(paste(x, " is odd."))
  }
}

divideCheck(x)

Please enter a number : 7
[1] "7  is odd."